language: python
python: '3.5'
sudo: false
env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
  matrix:
    - TOXENV=check
    - TOXENV=docs

    - TOXENV=py26-pytest28-pygal20-nodist-cover,coveralls,codecov
    - TOXENV=py26-pytest28-pygal20-nodist-nocov
    - TOXENV=py26-pytest28-pygal20-xdist-cover,coveralls,codecov
    - TOXENV=py26-pytest28-pygal20-xdist-nocov
    - TOXENV=py26-pytest28-pygal21-nodist-cover,coveralls,codecov
    - TOXENV=py26-pytest28-pygal21-nodist-nocov
    - TOXENV=py26-pytest28-pygal21-xdist-cover,coveralls,codecov
    - TOXENV=py26-pytest28-pygal21-xdist-nocov
    - TOXENV=py26-pytest28-pygal22-nodist-cover,coveralls,codecov
    - TOXENV=py26-pytest28-pygal22-nodist-nocov
    - TOXENV=py26-pytest28-pygal22-xdist-cover,coveralls,codecov
    - TOXENV=py26-pytest28-pygal22-xdist-nocov
    - TOXENV=py26-pytest28-pygal23-nodist-cover,coveralls,codecov
    - TOXENV=py26-pytest28-pygal23-nodist-nocov
    - TOXENV=py26-pytest28-pygal23-xdist-cover,coveralls,codecov
    - TOXENV=py26-pytest28-pygal23-xdist-nocov
    - TOXENV=py26-pytest29-pygal20-nodist-cover,coveralls,codecov
    - TOXENV=py26-pytest29-pygal20-nodist-nocov
    - TOXENV=py26-pytest29-pygal20-xdist-cover,coveralls,codecov
    - TOXENV=py26-pytest29-pygal20-xdist-nocov
    - TOXENV=py26-pytest29-pygal21-nodist-cover,coveralls,codecov
    - TOXENV=py26-pytest29-pygal21-nodist-nocov
    - TOXENV=py26-pytest29-pygal21-xdist-cover,coveralls,codecov
    - TOXENV=py26-pytest29-pygal21-xdist-nocov
    - TOXENV=py26-pytest29-pygal22-nodist-cover,coveralls,codecov
    - TOXENV=py26-pytest29-pygal22-nodist-nocov
    - TOXENV=py26-pytest29-pygal22-xdist-cover,coveralls,codecov
    - TOXENV=py26-pytest29-pygal22-xdist-nocov
    - TOXENV=py26-pytest29-pygal23-nodist-cover,coveralls,codecov
    - TOXENV=py26-pytest29-pygal23-nodist-nocov
    - TOXENV=py26-pytest29-pygal23-xdist-cover,coveralls,codecov
    - TOXENV=py26-pytest29-pygal23-xdist-nocov
    - TOXENV=py26-pytest30-pygal20-nodist-cover,coveralls,codecov
    - TOXENV=py26-pytest30-pygal20-nodist-nocov
    - TOXENV=py26-pytest30-pygal20-xdist-cover,coveralls,codecov
    - TOXENV=py26-pytest30-pygal20-xdist-nocov
    - TOXENV=py26-pytest30-pygal21-nodist-cover,coveralls,codecov
    - TOXENV=py26-pytest30-pygal21-nodist-nocov
    - TOXENV=py26-pytest30-pygal21-xdist-cover,coveralls,codecov
    - TOXENV=py26-pytest30-pygal21-xdist-nocov
    - TOXENV=py26-pytest30-pygal22-nodist-cover,coveralls,codecov
    - TOXENV=py26-pytest30-pygal22-nodist-nocov
    - TOXENV=py26-pytest30-pygal22-xdist-cover,coveralls,codecov
    - TOXENV=py26-pytest30-pygal22-xdist-nocov
    - TOXENV=py26-pytest30-pygal23-nodist-cover,coveralls,codecov
    - TOXENV=py26-pytest30-pygal23-nodist-nocov
    - TOXENV=py26-pytest30-pygal23-xdist-cover,coveralls,codecov
    - TOXENV=py26-pytest30-pygal23-xdist-nocov
    - TOXENV=py27-pytest28-pygal20-nodist-cover,coveralls,codecov
    - TOXENV=py27-pytest28-pygal20-nodist-nocov
    - TOXENV=py27-pytest28-pygal20-xdist-cover,coveralls,codecov
    - TOXENV=py27-pytest28-pygal20-xdist-nocov
    - TOXENV=py27-pytest28-pygal21-nodist-cover,coveralls,codecov
    - TOXENV=py27-pytest28-pygal21-nodist-nocov
    - TOXENV=py27-pytest28-pygal21-xdist-cover,coveralls,codecov
    - TOXENV=py27-pytest28-pygal21-xdist-nocov
    - TOXENV=py27-pytest28-pygal22-nodist-cover,coveralls,codecov
    - TOXENV=py27-pytest28-pygal22-nodist-nocov
    - TOXENV=py27-pytest28-pygal22-xdist-cover,coveralls,codecov
    - TOXENV=py27-pytest28-pygal22-xdist-nocov
    - TOXENV=py27-pytest28-pygal23-nodist-cover,coveralls,codecov
    - TOXENV=py27-pytest28-pygal23-nodist-nocov
    - TOXENV=py27-pytest28-pygal23-xdist-cover,coveralls,codecov
    - TOXENV=py27-pytest28-pygal23-xdist-nocov
    - TOXENV=py27-pytest29-pygal20-nodist-cover,coveralls,codecov
    - TOXENV=py27-pytest29-pygal20-nodist-nocov
    - TOXENV=py27-pytest29-pygal20-xdist-cover,coveralls,codecov
    - TOXENV=py27-pytest29-pygal20-xdist-nocov
    - TOXENV=py27-pytest29-pygal21-nodist-cover,coveralls,codecov
    - TOXENV=py27-pytest29-pygal21-nodist-nocov
    - TOXENV=py27-pytest29-pygal21-xdist-cover,coveralls,codecov
    - TOXENV=py27-pytest29-pygal21-xdist-nocov
    - TOXENV=py27-pytest29-pygal22-nodist-cover,coveralls,codecov
    - TOXENV=py27-pytest29-pygal22-nodist-nocov
    - TOXENV=py27-pytest29-pygal22-xdist-cover,coveralls,codecov
    - TOXENV=py27-pytest29-pygal22-xdist-nocov
    - TOXENV=py27-pytest29-pygal23-nodist-cover,coveralls,codecov
    - TOXENV=py27-pytest29-pygal23-nodist-nocov
    - TOXENV=py27-pytest29-pygal23-xdist-cover,coveralls,codecov
    - TOXENV=py27-pytest29-pygal23-xdist-nocov
    - TOXENV=py27-pytest30-pygal20-nodist-cover,coveralls,codecov
    - TOXENV=py27-pytest30-pygal20-nodist-nocov
    - TOXENV=py27-pytest30-pygal20-xdist-cover,coveralls,codecov
    - TOXENV=py27-pytest30-pygal20-xdist-nocov
    - TOXENV=py27-pytest30-pygal21-nodist-cover,coveralls,codecov
    - TOXENV=py27-pytest30-pygal21-nodist-nocov
    - TOXENV=py27-pytest30-pygal21-xdist-cover,coveralls,codecov
    - TOXENV=py27-pytest30-pygal21-xdist-nocov
    - TOXENV=py27-pytest30-pygal22-nodist-cover,coveralls,codecov
    - TOXENV=py27-pytest30-pygal22-nodist-nocov
    - TOXENV=py27-pytest30-pygal22-xdist-cover,coveralls,codecov
    - TOXENV=py27-pytest30-pygal22-xdist-nocov
    - TOXENV=py27-pytest30-pygal23-nodist-cover,coveralls,codecov
    - TOXENV=py27-pytest30-pygal23-nodist-nocov
    - TOXENV=py27-pytest30-pygal23-xdist-cover,coveralls,codecov
    - TOXENV=py27-pytest30-pygal23-xdist-nocov
    - TOXENV=py32-pytest28-pygal20-nodist-cover,coveralls,codecov
    - TOXENV=py32-pytest28-pygal20-nodist-nocov
    - TOXENV=py32-pytest28-pygal20-xdist-cover,coveralls,codecov
    - TOXENV=py32-pytest28-pygal20-xdist-nocov
    - TOXENV=py32-pytest28-pygal21-nodist-cover,coveralls,codecov
    - TOXENV=py32-pytest28-pygal21-nodist-nocov
    - TOXENV=py32-pytest28-pygal21-xdist-cover,coveralls,codecov
    - TOXENV=py32-pytest28-pygal21-xdist-nocov
    - TOXENV=py32-pytest28-pygal22-nodist-cover,coveralls,codecov
    - TOXENV=py32-pytest28-pygal22-nodist-nocov
    - TOXENV=py32-pytest28-pygal22-xdist-cover,coveralls,codecov
    - TOXENV=py32-pytest28-pygal22-xdist-nocov
    - TOXENV=py32-pytest28-pygal23-nodist-cover,coveralls,codecov
    - TOXENV=py32-pytest28-pygal23-nodist-nocov
    - TOXENV=py32-pytest28-pygal23-xdist-cover,coveralls,codecov
    - TOXENV=py32-pytest28-pygal23-xdist-nocov
    - TOXENV=py32-pytest29-pygal20-nodist-cover,coveralls,codecov
    - TOXENV=py32-pytest29-pygal20-nodist-nocov
    - TOXENV=py32-pytest29-pygal20-xdist-cover,coveralls,codecov
    - TOXENV=py32-pytest29-pygal20-xdist-nocov
    - TOXENV=py32-pytest29-pygal21-nodist-cover,coveralls,codecov
    - TOXENV=py32-pytest29-pygal21-nodist-nocov
    - TOXENV=py32-pytest29-pygal21-xdist-cover,coveralls,codecov
    - TOXENV=py32-pytest29-pygal21-xdist-nocov
    - TOXENV=py32-pytest29-pygal22-nodist-cover,coveralls,codecov
    - TOXENV=py32-pytest29-pygal22-nodist-nocov
    - TOXENV=py32-pytest29-pygal22-xdist-cover,coveralls,codecov
    - TOXENV=py32-pytest29-pygal22-xdist-nocov
    - TOXENV=py32-pytest29-pygal23-nodist-cover,coveralls,codecov
    - TOXENV=py32-pytest29-pygal23-nodist-nocov
    - TOXENV=py32-pytest29-pygal23-xdist-cover,coveralls,codecov
    - TOXENV=py32-pytest29-pygal23-xdist-nocov
    - TOXENV=py32-pytest30-pygal20-nodist-cover,coveralls,codecov
    - TOXENV=py32-pytest30-pygal20-nodist-nocov
    - TOXENV=py32-pytest30-pygal20-xdist-cover,coveralls,codecov
    - TOXENV=py32-pytest30-pygal20-xdist-nocov
    - TOXENV=py32-pytest30-pygal21-nodist-cover,coveralls,codecov
    - TOXENV=py32-pytest30-pygal21-nodist-nocov
    - TOXENV=py32-pytest30-pygal21-xdist-cover,coveralls,codecov
    - TOXENV=py32-pytest30-pygal21-xdist-nocov
    - TOXENV=py32-pytest30-pygal22-nodist-cover,coveralls,codecov
    - TOXENV=py32-pytest30-pygal22-nodist-nocov
    - TOXENV=py32-pytest30-pygal22-xdist-cover,coveralls,codecov
    - TOXENV=py32-pytest30-pygal22-xdist-nocov
    - TOXENV=py32-pytest30-pygal23-nodist-cover,coveralls,codecov
    - TOXENV=py32-pytest30-pygal23-nodist-nocov
    - TOXENV=py32-pytest30-pygal23-xdist-cover,coveralls,codecov
    - TOXENV=py32-pytest30-pygal23-xdist-nocov
    - TOXENV=py33-pytest28-pygal20-nodist-cover,coveralls,codecov
    - TOXENV=py33-pytest28-pygal20-nodist-nocov
    - TOXENV=py33-pytest28-pygal20-xdist-cover,coveralls,codecov
    - TOXENV=py33-pytest28-pygal20-xdist-nocov
    - TOXENV=py33-pytest28-pygal21-nodist-cover,coveralls,codecov
    - TOXENV=py33-pytest28-pygal21-nodist-nocov
    - TOXENV=py33-pytest28-pygal21-xdist-cover,coveralls,codecov
    - TOXENV=py33-pytest28-pygal21-xdist-nocov
    - TOXENV=py33-pytest28-pygal22-nodist-cover,coveralls,codecov
    - TOXENV=py33-pytest28-pygal22-nodist-nocov
    - TOXENV=py33-pytest28-pygal22-xdist-cover,coveralls,codecov
    - TOXENV=py33-pytest28-pygal22-xdist-nocov
    - TOXENV=py33-pytest28-pygal23-nodist-cover,coveralls,codecov
    - TOXENV=py33-pytest28-pygal23-nodist-nocov
    - TOXENV=py33-pytest28-pygal23-xdist-cover,coveralls,codecov
    - TOXENV=py33-pytest28-pygal23-xdist-nocov
    - TOXENV=py33-pytest29-pygal20-nodist-cover,coveralls,codecov
    - TOXENV=py33-pytest29-pygal20-nodist-nocov
    - TOXENV=py33-pytest29-pygal20-xdist-cover,coveralls,codecov
    - TOXENV=py33-pytest29-pygal20-xdist-nocov
    - TOXENV=py33-pytest29-pygal21-nodist-cover,coveralls,codecov
    - TOXENV=py33-pytest29-pygal21-nodist-nocov
    - TOXENV=py33-pytest29-pygal21-xdist-cover,coveralls,codecov
    - TOXENV=py33-pytest29-pygal21-xdist-nocov
    - TOXENV=py33-pytest29-pygal22-nodist-cover,coveralls,codecov
    - TOXENV=py33-pytest29-pygal22-nodist-nocov
    - TOXENV=py33-pytest29-pygal22-xdist-cover,coveralls,codecov
    - TOXENV=py33-pytest29-pygal22-xdist-nocov
    - TOXENV=py33-pytest29-pygal23-nodist-cover,coveralls,codecov
    - TOXENV=py33-pytest29-pygal23-nodist-nocov
    - TOXENV=py33-pytest29-pygal23-xdist-cover,coveralls,codecov
    - TOXENV=py33-pytest29-pygal23-xdist-nocov
    - TOXENV=py33-pytest30-pygal20-nodist-cover,coveralls,codecov
    - TOXENV=py33-pytest30-pygal20-nodist-nocov
    - TOXENV=py33-pytest30-pygal20-xdist-cover,coveralls,codecov
    - TOXENV=py33-pytest30-pygal20-xdist-nocov
    - TOXENV=py33-pytest30-pygal21-nodist-cover,coveralls,codecov
    - TOXENV=py33-pytest30-pygal21-nodist-nocov
    - TOXENV=py33-pytest30-pygal21-xdist-cover,coveralls,codecov
    - TOXENV=py33-pytest30-pygal21-xdist-nocov
    - TOXENV=py33-pytest30-pygal22-nodist-cover,coveralls,codecov
    - TOXENV=py33-pytest30-pygal22-nodist-nocov
    - TOXENV=py33-pytest30-pygal22-xdist-cover,coveralls,codecov
    - TOXENV=py33-pytest30-pygal22-xdist-nocov
    - TOXENV=py33-pytest30-pygal23-nodist-cover,coveralls,codecov
    - TOXENV=py33-pytest30-pygal23-nodist-nocov
    - TOXENV=py33-pytest30-pygal23-xdist-cover,coveralls,codecov
    - TOXENV=py33-pytest30-pygal23-xdist-nocov
    - TOXENV=py34-pytest28-pygal20-nodist-cover,coveralls,codecov
    - TOXENV=py34-pytest28-pygal20-nodist-nocov
    - TOXENV=py34-pytest28-pygal20-xdist-cover,coveralls,codecov
    - TOXENV=py34-pytest28-pygal20-xdist-nocov
    - TOXENV=py34-pytest28-pygal21-nodist-cover,coveralls,codecov
    - TOXENV=py34-pytest28-pygal21-nodist-nocov
    - TOXENV=py34-pytest28-pygal21-xdist-cover,coveralls,codecov
    - TOXENV=py34-pytest28-pygal21-xdist-nocov
    - TOXENV=py34-pytest28-pygal22-nodist-cover,coveralls,codecov
    - TOXENV=py34-pytest28-pygal22-nodist-nocov
    - TOXENV=py34-pytest28-pygal22-xdist-cover,coveralls,codecov
    - TOXENV=py34-pytest28-pygal22-xdist-nocov
    - TOXENV=py34-pytest28-pygal23-nodist-cover,coveralls,codecov
    - TOXENV=py34-pytest28-pygal23-nodist-nocov
    - TOXENV=py34-pytest28-pygal23-xdist-cover,coveralls,codecov
    - TOXENV=py34-pytest28-pygal23-xdist-nocov
    - TOXENV=py34-pytest29-pygal20-nodist-cover,coveralls,codecov
    - TOXENV=py34-pytest29-pygal20-nodist-nocov
    - TOXENV=py34-pytest29-pygal20-xdist-cover,coveralls,codecov
    - TOXENV=py34-pytest29-pygal20-xdist-nocov
    - TOXENV=py34-pytest29-pygal21-nodist-cover,coveralls,codecov
    - TOXENV=py34-pytest29-pygal21-nodist-nocov
    - TOXENV=py34-pytest29-pygal21-xdist-cover,coveralls,codecov
    - TOXENV=py34-pytest29-pygal21-xdist-nocov
    - TOXENV=py34-pytest29-pygal22-nodist-cover,coveralls,codecov
    - TOXENV=py34-pytest29-pygal22-nodist-nocov
    - TOXENV=py34-pytest29-pygal22-xdist-cover,coveralls,codecov
    - TOXENV=py34-pytest29-pygal22-xdist-nocov
    - TOXENV=py34-pytest29-pygal23-nodist-cover,coveralls,codecov
    - TOXENV=py34-pytest29-pygal23-nodist-nocov
    - TOXENV=py34-pytest29-pygal23-xdist-cover,coveralls,codecov
    - TOXENV=py34-pytest29-pygal23-xdist-nocov
    - TOXENV=py34-pytest30-pygal20-nodist-cover,coveralls,codecov
    - TOXENV=py34-pytest30-pygal20-nodist-nocov
    - TOXENV=py34-pytest30-pygal20-xdist-cover,coveralls,codecov
    - TOXENV=py34-pytest30-pygal20-xdist-nocov
    - TOXENV=py34-pytest30-pygal21-nodist-cover,coveralls,codecov
    - TOXENV=py34-pytest30-pygal21-nodist-nocov
    - TOXENV=py34-pytest30-pygal21-xdist-cover,coveralls,codecov
    - TOXENV=py34-pytest30-pygal21-xdist-nocov
    - TOXENV=py34-pytest30-pygal22-nodist-cover,coveralls,codecov
    - TOXENV=py34-pytest30-pygal22-nodist-nocov
    - TOXENV=py34-pytest30-pygal22-xdist-cover,coveralls,codecov
    - TOXENV=py34-pytest30-pygal22-xdist-nocov
    - TOXENV=py34-pytest30-pygal23-nodist-cover,coveralls,codecov
    - TOXENV=py34-pytest30-pygal23-nodist-nocov
    - TOXENV=py34-pytest30-pygal23-xdist-cover,coveralls,codecov
    - TOXENV=py34-pytest30-pygal23-xdist-nocov
    - TOXENV=py35-pytest28-pygal20-nodist-cover,coveralls,codecov
    - TOXENV=py35-pytest28-pygal20-nodist-nocov
    - TOXENV=py35-pytest28-pygal20-xdist-cover,coveralls,codecov
    - TOXENV=py35-pytest28-pygal20-xdist-nocov
    - TOXENV=py35-pytest28-pygal21-nodist-cover,coveralls,codecov
    - TOXENV=py35-pytest28-pygal21-nodist-nocov
    - TOXENV=py35-pytest28-pygal21-xdist-cover,coveralls,codecov
    - TOXENV=py35-pytest28-pygal21-xdist-nocov
    - TOXENV=py35-pytest28-pygal22-nodist-cover,coveralls,codecov
    - TOXENV=py35-pytest28-pygal22-nodist-nocov
    - TOXENV=py35-pytest28-pygal22-xdist-cover,coveralls,codecov
    - TOXENV=py35-pytest28-pygal22-xdist-nocov
    - TOXENV=py35-pytest28-pygal23-nodist-cover,coveralls,codecov
    - TOXENV=py35-pytest28-pygal23-nodist-nocov
    - TOXENV=py35-pytest28-pygal23-xdist-cover,coveralls,codecov
    - TOXENV=py35-pytest28-pygal23-xdist-nocov
    - TOXENV=py35-pytest29-pygal20-nodist-cover,coveralls,codecov
    - TOXENV=py35-pytest29-pygal20-nodist-nocov
    - TOXENV=py35-pytest29-pygal20-xdist-cover,coveralls,codecov
    - TOXENV=py35-pytest29-pygal20-xdist-nocov
    - TOXENV=py35-pytest29-pygal21-nodist-cover,coveralls,codecov
    - TOXENV=py35-pytest29-pygal21-nodist-nocov
    - TOXENV=py35-pytest29-pygal21-xdist-cover,coveralls,codecov
    - TOXENV=py35-pytest29-pygal21-xdist-nocov
    - TOXENV=py35-pytest29-pygal22-nodist-cover,coveralls,codecov
    - TOXENV=py35-pytest29-pygal22-nodist-nocov
    - TOXENV=py35-pytest29-pygal22-xdist-cover,coveralls,codecov
    - TOXENV=py35-pytest29-pygal22-xdist-nocov
    - TOXENV=py35-pytest29-pygal23-nodist-cover,coveralls,codecov
    - TOXENV=py35-pytest29-pygal23-nodist-nocov
    - TOXENV=py35-pytest29-pygal23-xdist-cover,coveralls,codecov
    - TOXENV=py35-pytest29-pygal23-xdist-nocov
    - TOXENV=py35-pytest30-pygal20-nodist-cover,coveralls,codecov
    - TOXENV=py35-pytest30-pygal20-nodist-nocov
    - TOXENV=py35-pytest30-pygal20-xdist-cover,coveralls,codecov
    - TOXENV=py35-pytest30-pygal20-xdist-nocov
    - TOXENV=py35-pytest30-pygal21-nodist-cover,coveralls,codecov
    - TOXENV=py35-pytest30-pygal21-nodist-nocov
    - TOXENV=py35-pytest30-pygal21-xdist-cover,coveralls,codecov
    - TOXENV=py35-pytest30-pygal21-xdist-nocov
    - TOXENV=py35-pytest30-pygal22-nodist-cover,coveralls,codecov
    - TOXENV=py35-pytest30-pygal22-nodist-nocov
    - TOXENV=py35-pytest30-pygal22-xdist-cover,coveralls,codecov
    - TOXENV=py35-pytest30-pygal22-xdist-nocov
    - TOXENV=py35-pytest30-pygal23-nodist-cover,coveralls,codecov
    - TOXENV=py35-pytest30-pygal23-nodist-nocov
    - TOXENV=py35-pytest30-pygal23-xdist-cover,coveralls,codecov
    - TOXENV=py35-pytest30-pygal23-xdist-nocov
    - TOXENV=pypy-pytest28-pygal20-nodist-cover,coveralls,codecov
    - TOXENV=pypy-pytest28-pygal20-nodist-nocov
    - TOXENV=pypy-pytest28-pygal20-xdist-cover,coveralls,codecov
    - TOXENV=pypy-pytest28-pygal20-xdist-nocov
    - TOXENV=pypy-pytest28-pygal21-nodist-cover,coveralls,codecov
    - TOXENV=pypy-pytest28-pygal21-nodist-nocov
    - TOXENV=pypy-pytest28-pygal21-xdist-cover,coveralls,codecov
    - TOXENV=pypy-pytest28-pygal21-xdist-nocov
    - TOXENV=pypy-pytest28-pygal22-nodist-cover,coveralls,codecov
    - TOXENV=pypy-pytest28-pygal22-nodist-nocov
    - TOXENV=pypy-pytest28-pygal22-xdist-cover,coveralls,codecov
    - TOXENV=pypy-pytest28-pygal22-xdist-nocov
    - TOXENV=pypy-pytest28-pygal23-nodist-cover,coveralls,codecov
    - TOXENV=pypy-pytest28-pygal23-nodist-nocov
    - TOXENV=pypy-pytest28-pygal23-xdist-cover,coveralls,codecov
    - TOXENV=pypy-pytest28-pygal23-xdist-nocov
    - TOXENV=pypy-pytest29-pygal20-nodist-cover,coveralls,codecov
    - TOXENV=pypy-pytest29-pygal20-nodist-nocov
    - TOXENV=pypy-pytest29-pygal20-xdist-cover,coveralls,codecov
    - TOXENV=pypy-pytest29-pygal20-xdist-nocov
    - TOXENV=pypy-pytest29-pygal21-nodist-cover,coveralls,codecov
    - TOXENV=pypy-pytest29-pygal21-nodist-nocov
    - TOXENV=pypy-pytest29-pygal21-xdist-cover,coveralls,codecov
    - TOXENV=pypy-pytest29-pygal21-xdist-nocov
    - TOXENV=pypy-pytest29-pygal22-nodist-cover,coveralls,codecov
    - TOXENV=pypy-pytest29-pygal22-nodist-nocov
    - TOXENV=pypy-pytest29-pygal22-xdist-cover,coveralls,codecov
    - TOXENV=pypy-pytest29-pygal22-xdist-nocov
    - TOXENV=pypy-pytest29-pygal23-nodist-cover,coveralls,codecov
    - TOXENV=pypy-pytest29-pygal23-nodist-nocov
    - TOXENV=pypy-pytest29-pygal23-xdist-cover,coveralls,codecov
    - TOXENV=pypy-pytest29-pygal23-xdist-nocov
    - TOXENV=pypy-pytest30-pygal20-nodist-cover,coveralls,codecov
    - TOXENV=pypy-pytest30-pygal20-nodist-nocov
    - TOXENV=pypy-pytest30-pygal20-xdist-cover,coveralls,codecov
    - TOXENV=pypy-pytest30-pygal20-xdist-nocov
    - TOXENV=pypy-pytest30-pygal21-nodist-cover,coveralls,codecov
    - TOXENV=pypy-pytest30-pygal21-nodist-nocov
    - TOXENV=pypy-pytest30-pygal21-xdist-cover,coveralls,codecov
    - TOXENV=pypy-pytest30-pygal21-xdist-nocov
    - TOXENV=pypy-pytest30-pygal22-nodist-cover,coveralls,codecov
    - TOXENV=pypy-pytest30-pygal22-nodist-nocov
    - TOXENV=pypy-pytest30-pygal22-xdist-cover,coveralls,codecov
    - TOXENV=pypy-pytest30-pygal22-xdist-nocov
    - TOXENV=pypy-pytest30-pygal23-nodist-cover,coveralls,codecov
    - TOXENV=pypy-pytest30-pygal23-nodist-nocov
    - TOXENV=pypy-pytest30-pygal23-xdist-cover,coveralls,codecov
    - TOXENV=pypy-pytest30-pygal23-xdist-nocov
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install -U tox setuptools wheel $(python -V |& grep -q 'Python 3.2' && echo 'pip<8.0 virtualenv<14.0')
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version
script:
  - tox -v
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
before_cache:
  - rm -rf $HOME/.cache/pip/log
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email:
    on_success: never
    on_failure: always
